name: Run template tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@a138926f6e4f9667d1306c24f24f5bdcaa01fbab  # v2.5.0
    with:
      envs: |
        - macos: py312-test
        - linux: py313-test
        - linux: py314-test
        - linux: build_docs

  bake_cookies:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@a138926f6e4f9667d1306c24f24f5bdcaa01fbab  # v2.5.0
    with:
      artifact-path: |
        cookies
      envs: |
        - linux: bake_cookies
