name: Run template tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@8c8bb6c6c962542921f993d47d26df38dccd50b1 # v3.0.2
    with:
      envs: |
        - macos: py312-test
        - linux: py313-test
        - linux: py314-test
        - linux: build_docs

  bake_cookies:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@8c8bb6c6c962542921f993d47d26df38dccd50b1 # v3.0.2
    with:
      artifact-path: |
        cookies
        cookies/.**
      artifact-include-hidden-files: true
      envs: |
        - linux: bake_cookies
