name: Run template tests

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@2835f0cacddf3f8de198db9afdb5354a5cebe0ef # v2.6.3
    with:
      envs: |
        - macos: py312-test
        - linux: py313-test
        - linux: py314-test
        - linux: build_docs

  bake_cookies:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@2835f0cacddf3f8de198db9afdb5354a5cebe0ef # v2.6.3
    with:
      artifact-path: |
        cookies
        cookies/.**
      artifact-include-hidden-files: true
      envs: |
        - linux: bake_cookies
